# Generated by Django 3.2.3 on 2021-05-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('start_date', models.CharField(max_length=200)),
                ('end_date', models.CharField(max_length=200)),
                ('main_photo', models.ImageField(upload_to='photos/main/%Y/%m/%d/')),
                ('photo1', models.ImageField(blank=True, upload_to='photos/optional/%Y/%m/%d/')),
                ('photo2', models.ImageField(blank=True, upload_to='photos/optional/%Y/%m/%d/')),
                ('photo3', models.ImageField(blank=True, upload_to='photos/optional/%Y/%m/%d/')),
                ('photo4', models.ImageField(blank=True, upload_to='photos/optional/%Y/%m/%d/')),
                ('photo5', models.ImageField(blank=True, upload_to='photos/optional/%Y/%m/%d/')),
                ('photo6', models.ImageField(blank=True, upload_to='photos/optional/%Y/%m/%d/')),
                ('photo7', models.ImageField(blank=True, upload_to='photos/optional/%Y/%m/%d/')),
                ('photo8', models.ImageField(blank=True, upload_to='photos/optional/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('member_type', models.CharField(choices=[('scom', 'Scom'), ('jcom', 'Jcom')], default='jcom', max_length=10)),
                ('member_photo', models.ImageField(upload_to='photos/seller/%Y/%m/%d/')),
                ('instagram', models.CharField(blank=True, max_length=200)),
                ('linkedin', models.CharField(blank=True, max_length=200)),
                ('facebook', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
