# Generated by Django 3.2.3 on 2021-05-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('query', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='seq',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
