# Generated by Django 3.2.3 on 2021-05-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csiapp', '0002_auto_20210531_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='query',
            new_name='subject',
        ),
        migrations.AddField(
            model_name='contact',
            name='description',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
