# Generated by Django 3.2.3 on 2021-05-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csiapp', '0003_auto_20210531_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
